// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    About: typeof import('./src/components/About.vue')['default']
    BottomNavigation: typeof import('./src/components/BottomNavigation.vue')['default']
    ContactHero: typeof import('./src/components/ContactHero.vue')['default']
    HomeHero: typeof import('./src/components/HomeHero.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Testimonials: typeof import('./src/components/Testimonials.vue')['default']
    TopNavigation: typeof import('./src/components/TopNavigation.vue')['default']
  }
}

export {}
